//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IlmdostPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int application_id { get; set; }
        public Nullable<int> job_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> application_date { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
